package com.dhevi.ibox.model

import com.dhevi.ibox.R

object FakeIboxDataSource {
    val dummyIboxes = listOf(
        Ibox(1,
            R.drawable.iphone_1,
            "Iphone 14 Pro Max 512GB",
            "White Titanium",
            23999000,
            "Layar iPhone 14 Pro memiliki sudut melengkung yang mengikuti desain lekukan yang indah, dan semua sudut ini berada di dalam bidang persegi standar. Jika diukur sebagai bentuk persegi standar, layarnya berukuran 6,68 inci secara diagonal (area bidang layar berukuran lebih kecil)"),
        Ibox(2,
            R.drawable.iphone_2,
            "Iphone 15 Pro Max 256GB",
            "Deep Purple",
            24999000,
            "iPhone 15 Pro merupakan iPhone pertama dengan desain titanium sekelas industri dirgantara, menggunakan paduan logam yang sama dengan pesawat luar angkasa untuk misi ke Mars."),
        Ibox(3,
            R.drawable.ipadpro,
            "iPad Pro Generasi 6 512GB",
            "Silver Glossy",
            13640000,
            "Performa menakjubkan. Layar luar biasa canggih. Konektivitas nirkabel super cepat. Kemampuan Apple Pencil di level berikutnya. Fitur baru yang andal di iPadOS. Pengalaman iPad terbaik."),
        Ibox(4,
            R.drawable.ipad_mini,
            "iPad Mini Generasi 5 256GB",
            "Purple Glossy",
            24999000,
            "iPad mini dirancang dengan cermat dan begitu memikat. Penutup yang sepenuhnya baru dengan layar baru yang lebih besar membentang dari ujung ke ujung, serta tepian yang tipis dan sudut melengkung yang elegan."),
        Ibox(5,
            R.drawable.macbook,
            "Apple Macbook Pro M2 512GB",
            "GraySilver",
            20900000,
            "Chip M2 baru menjadikan MacBook Pro 13 inci semakin andal. Desain ringkas yang sama mendukung kekuatan baterai hingga 20 jam1 dan sistem pendingin aktif untuk mempertahankan kinerja yang ditingkatkan. Dilengkapi layar Retina cemerlang, kamera FaceTime HD, dan mikrofon kualitas studio, inilah laptop pro kami yang paling portabel."),
        Ibox(6,
            R.drawable.airpods,
            "AirPods Pro Waterproof",
            "White Dove",
            3424000,
            "Chip H2 rancangan Apple adalah kekuatan di balik AirPods Pro dan performa audionya yang canggih. Chip ini bekerja harmonis dengan driver dan amplifier yang dibuat khusus untuk menghasilkan nada tinggi, jernih, dan tajam serta bass yang dalam dan menggelegar lewat definisi yang memukau — sehingga setiap suara terdengar semakin hidup.\n" +
                    "\n"),
        Ibox(7,
            R.drawable.airpods_2,
            "AirPods Waterproof",
            "White Glossy",
            1694000,
            "Mikrofon tertanam dalam setiap earbud yang dilapisi dengan jaring akustik khusus meminimalisir derau angin ketika Anda melakukan panggilan — jadi suara Anda selalu terdengar nyaring dan jelas."),
        Ibox(8,
            R.drawable.airtag,
            "AirTag (4 Pack) 25mm",
            "Silver",
            24999000,
            "AirTag adalah cara mudah untuk melacak barang-barang Anda. Tempel satu di kunci Anda. Satu lagi di tas Anda. Dengan begitu, barang-barang tersebut terpantau melalui aplikasi Lacak, yang juga dapat menemukan perangkat Apple Anda serta terhubung dengan teman dan keluarga."),
        Ibox(9,
            R.drawable.imac,
            "iMac M1 SSD 256GB",
            "White Glossy",
            1650000,
            "Desain luar biasa ini dimungkinkan berkat M1, sistem pertama dalam sebuah chip untuk Mac. Membuat iMac begitu tipis dan ringkas, sehingga pas diletakkan di mana saja."),
        Ibox(10,
            R.drawable.imac_2,
            "iMac 24 SSD 2TB",
            "Clear White",
            24899000,
            "Desain luar biasa ini dimungkinkan berkat M1, sistem pertama dalam sebuah chip untuk Mac. Membuat iMac begitu tipis dan ringkas, sehingga pas diletakkan di mana saja."),
        Ibox(11,
            R.drawable.iwatch,
            "Apple Watch Ultra 2 49MM",
            "Night Midnight",
            12705000,
            "Apple Watch Ultra 2 dirancang untuk performa tak tertandingi. Casing titanium ringan yang tangguh dan tahan korosi, dengan tepian yang membalut untuk melindungi kristal safir apabila tepiannya terbentur."),
        Ibox(12,
            R.drawable.iwatch_white,
            "Apple Watch Series 8",
            "Silver White",
            5389000,
            "Apple Watch Ultra 2 dirancang untuk performa tak tertandingi. Casing titanium ringan yang tangguh dan tahan korosi, dengan tepian yang membalut untuk melindungi kristal safir apabila tepiannya terbentur."),
    )
}